### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by prgrobots** [andreacioni/actionpi#12]
I have pip installed the software but I cant figure out how to use it. 

Was it something to do with this warning?

![image](https://github.com/andreacioni/actionpi/assets/91106994/4f3d4474-5c3c-4b34-9722-ae4bcf5c1853)

I can't seem to find any guides or info either

**Comment by andreacioni** [comment]
Hi @prgrobots, this project of mine is in stale due to other priorities. I was thinking to add a section on the wiki to let people install it themselves but never had time. 

Consider that _the easy way_ to use it should be the one described here: https://github.com/andreacioni/actionpi/wiki/2.-Getting-Started#write-sd-card-image . Unfortunately I've never uploaded the image due to lack of interest from the public.

However if you are interested I could upload the latest version I'm using so you could test it.

**Comment by prgrobots** [comment]
I'd love to try the latest image if you have one :)

**Comment by prgrobots** [comment]
I've got this version working, except the camera.  
The camera works when I test it with `libcamera-still -o test.jpg`

No preview and 0kb files when I use the web interface to start recording

**Comment by andreacioni** [comment]
> I'd love to try the latest image if you have one :)

Sure I'll try to upload my latest one.

> No preview and 0kb files when I use the web interface to start recording

What version are you running? Could you please run `pip3 show actionpi` ? Not sure how you are running the process but are there some logs you can share?

**Comment by prgrobots** [comment]
> 
Returns: 
`Name: actionpi
Version: 1.1.17
Summary: Action/Dash camera powered by Raspberry Pi Zero
Home-page: https://github.com/andreacioni/actionpi
Author: Andrea Cioni
Author-email: None
License: UNKNOWN
Location: /home/hellpi/.local/lib/python3.9/site-packages
Requires: flask-cors, gpiozero, picamera, pycommon-andreacioni, RPi.GPIO, flask-                                                                                                 restful, flask, psutil
Required-by:
`

**Comment by andreacioni** [comment]
Ok, the version is correct. Logs could help but I will upload the latest image in a couple of days so you'll have a good starting point.

**Comment by andreacioni** [comment]
You can find in the wiki the updated link to the latest version of the image. Let me know if it works for you too.

**Comment by prgrobots** [comment]
Awesome, thanks,  I'll try it out and get back to you.

**Comment by prgrobots** [comment]
![IMG20230718191519_00](http
Pressing enter doesn't do anything here.
Tried 2 keyboards.  

I haven't seen this error before?

![IMG20230718191519_00](https://github.com/andreacioni/actionpi/assets/91106994/e8a3a2d8-c9de-44e2-814b-3a09a62a06b9)


Flashed with balena this time and error has gone and everything thing seems to be working so far.

Strange the keyboard is still not working on the local terminal, might be my pi.

**Comment by prgrobots** [comment]
Is there a way to run this with debugging,  Its not recording.

**Comment by andreacioni** [comment]
It should be possible, however I've never did that. I suggest you to collect the logs and attach them here.
